# Generated by Django 2.1.12 on 2021-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCodeDefinitionMaster',
            fields=[
                ('品目グループコード', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('原価属性コード', models.CharField(max_length=2)),
                ('勘定コード', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': '勘定コード定義マスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountCodeMaster',
            fields=[
                ('勘定コード', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('テキスト短', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': '勘定コードマスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostCenterMaster',
            fields=[
                ('原価センタ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('原価センタテキスト', models.CharField(blank=True, max_length=20, null=True)),
                ('原価属性コード', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': '原価センタマスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstructionNoMaster',
            fields=[
                ('指図書コード', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('テキスト短', models.CharField(blank=True, max_length=40, null=True)),
                ('指図書タイプ', models.CharField(blank=True, max_length=4, null=True)),
                ('指図書タイプ名称', models.CharField(blank=True, max_length=30, null=True)),
                ('利益センター', models.CharField(blank=True, max_length=10, null=True)),
                ('指図ステータス', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
            ],
            options={
                'db_table': '指図書マスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemGroupMaster',
            fields=[
                ('品目グループコード', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('品目グループテキスト', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': '品目グループマスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('品目コード', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('テキスト品目コード', models.CharField(max_length=8)),
                ('プラントコード', models.CharField(max_length=4)),
                ('VB区分', models.CharField(max_length=1)),
                ('品目テキスト', models.CharField(blank=True, max_length=40, null=True)),
                ('基本数量単位', models.CharField(blank=True, max_length=3, null=True)),
                ('品目グループ', models.CharField(blank=True, max_length=9, null=True)),
                ('購買発注テキスト1', models.CharField(blank=True, max_length=40, null=True)),
                ('購買発注テキスト2', models.CharField(blank=True, max_length=40, null=True)),
                ('カタログ名', models.CharField(blank=True, max_length=25, null=True)),
                ('カタログNO', models.CharField(blank=True, max_length=15, null=True)),
                ('カタログページ', models.CharField(blank=True, max_length=20, null=True)),
                ('CASNO', models.CharField(blank=True, max_length=20, null=True)),
                ('レジストリNO', models.CharField(blank=True, max_length=1840, null=True)),
                ('商品備考1', models.CharField(blank=True, max_length=40, null=True)),
                ('商品備考2', models.CharField(blank=True, max_length=40, null=True)),
                ('商品備考3', models.CharField(blank=True, max_length=40, null=True)),
                ('商品備考4', models.CharField(blank=True, max_length=40, null=True)),
                ('発注日', models.CharField(blank=True, max_length=8, null=True)),
                ('発注価格', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('通貨コード', models.CharField(blank=True, max_length=5, null=True)),
                ('購買価格単位', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('発注仕入先コード', models.CharField(blank=True, max_length=10, null=True)),
                ('購買グループ', models.CharField(blank=True, max_length=4, null=True)),
                ('購買組織', models.CharField(blank=True, max_length=5, null=True)),
                ('発注NO', models.CharField(blank=True, max_length=10, null=True)),
                ('発注明細NO', models.CharField(blank=True, max_length=5, null=True)),
                ('バッチ処理フラグ', models.CharField(blank=True, max_length=1, null=True)),
                ('失効区分', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': '品目マスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDepartment',
            fields=[
                ('部署コード', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('部署名称', models.CharField(blank=True, max_length=40, null=True)),
                ('部署グループコード', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': '依頼部署マスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuantityUnitMaster',
            fields=[
                ('数量単位コード', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('単位テキスト', models.CharField(blank=True, max_length=30, null=True)),
                ('備考', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '数量単位マスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageSpaceMaster',
            fields=[
                ('プラントコード', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('保管場所コード', models.CharField(max_length=4)),
                ('保管場所テキスト', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': '保管場所マスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('NTユーザー名', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('会社コード', models.CharField(blank=True, max_length=4, null=True)),
                ('漢字氏名', models.CharField(blank=True, max_length=16, null=True)),
                ('社員コード', models.CharField(blank=True, max_length=8, null=True)),
                ('メールアドレス', models.CharField(blank=True, max_length=40, null=True)),
                ('部署コード', models.CharField(blank=True, max_length=4, null=True)),
                ('兼務部署コード1', models.CharField(blank=True, max_length=4, null=True)),
                ('兼務部署コード2', models.CharField(blank=True, max_length=4, null=True)),
                ('兼務部署コード3', models.CharField(blank=True, max_length=4, null=True)),
                ('兼務部署コード4', models.CharField(blank=True, max_length=4, null=True)),
                ('兼務部署コード5', models.CharField(blank=True, max_length=4, null=True)),
                ('兼務部署コード6', models.CharField(blank=True, max_length=4, null=True)),
                ('兼務部署コード7', models.CharField(blank=True, max_length=4, null=True)),
                ('兼務部署コード8', models.CharField(blank=True, max_length=4, null=True)),
                ('兼務部署コード9', models.CharField(blank=True, max_length=4, null=True)),
                ('兼務部署コード10', models.CharField(blank=True, max_length=4, null=True)),
                ('承認権限', models.CharField(blank=True, max_length=1, null=True)),
                ('システム権限', models.CharField(blank=True, max_length=1, null=True)),
                ('上長メールアドレス', models.CharField(blank=True, max_length=40, null=True)),
                ('代理メールアドレス1', models.CharField(blank=True, max_length=40, null=True)),
                ('代理メールアドレス2', models.CharField(blank=True, max_length=40, null=True)),
                ('代理メールアドレス3', models.CharField(blank=True, max_length=40, null=True)),
                ('代理メールアドレス4', models.CharField(blank=True, max_length=40, null=True)),
                ('代理メールアドレス5', models.CharField(blank=True, max_length=40, null=True)),
                ('購買依頼者', models.CharField(blank=True, max_length=12, null=True)),
                ('購買依頼追跡番号', models.CharField(blank=True, max_length=10, null=True)),
                ('プラントコード', models.CharField(blank=True, max_length=4, null=True)),
                ('購買グループ', models.CharField(blank=True, max_length=3, null=True)),
                ('担当別購買グループ', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'ユーザー管理マスタ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendorMaster',
            fields=[
                ('仕入先コード', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('仕入先名称', models.CharField(blank=True, max_length=40, null=True)),
                ('会社コード', models.CharField(blank=True, max_length=4, null=True)),
                ('購買組織コード', models.CharField(max_length=4)),
                ('購買発注通貨', models.CharField(blank=True, max_length=5, null=True)),
                ('購買グループコード', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': '仕入先マスタ',
                'managed': False,
            },
        ),
    ]
