# Generated by Django 2.1.12 on 2022-09-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcframe',
            name='purchase_order_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='購買発注NO '),
        ),
    ]
