from django.db import models


# 管理区分テーブル　(旧テーブル:MGT_CLS_MST)
class MasterMgtCls (models.Model):
    m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False, primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    mgt_cls = models.CharField(max_length=1, blank=False, null=False)
    mgt_cls_nm_1 = models.CharField(max_length=10, blank=False, null=False)
    mgt_cls_nm_2 = models.CharField(max_length=10, blank=True, null=True)
    mgt_cls_nm_3 = models.CharField(max_length=10, blank=True, null=True)
    mgt_cls_nm_4 = models.CharField(max_length=10, blank=True, null=True)
    mgt_cls_nm_5 = models.CharField(max_length=10, blank=True, null=True)
    fclty_alias_1 = models.CharField(max_length=10, blank=True, null=True)
    fclty_alias_2 = models.CharField(max_length=10, blank=True, null=True)
    fclty_alias_3 = models.CharField(max_length=10, blank=True, null=True)
    fclty_alias_4 = models.CharField(max_length=10, blank=True, null=True)
    fclty_alias_5 = models.CharField(max_length=10, blank=True, null=True)
    fclty_nm_alias_1 = models.CharField(max_length=10, blank=True, null=True)
    fclty_nm_alias_2 = models.CharField(max_length=10, blank=True, null=True)
    fclty_nm_alias_3 = models.CharField(max_length=10, blank=True, null=True)
    fclty_nm_alias_4 = models.CharField(max_length=10, blank=True, null=True)
    fclty_nm_alias_5 = models.CharField(max_length=10, blank=True, null=True)
    display_order = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'm_mgt_cls'


# ロケーションテーブル　(旧テーブル:工場マスタFCLTY_CD)
class MasterLocation (models.Model):
    m_location_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False, primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    location_cd = models.CharField(max_length=50, blank=False, null=False)
    location_nm_1 = models.CharField(max_length=1000, blank=False, null=False)
    location_nm_2 = models.CharField(max_length=1000, blank=True, null=True)
    location_nm_3 = models.CharField(max_length=1000, blank=True, null=True)
    location_nm_4 = models.CharField(max_length=1000, blank=True, null=True)
    location_nm_5 = models.CharField(max_length=1000, blank=True, null=True)
    parent_m_location_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    location_in_chrg_s_user_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    display_order = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)
    location_abbr_1 = models.CharField(max_length=1000, blank=True, null=True)
    location_abbr_2 = models.CharField(max_length=1000, blank=True, null=True)
    location_abbr_3 = models.CharField(max_length=1000, blank=True, null=True)
    location_abbr_4 = models.CharField(max_length=1000, blank=True, null=True)
    location_abbr_5 = models.CharField(max_length=1000, blank=True, null=True)
    rem = models.CharField(max_length=2000, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'm_location'


# 実施区分マスタ
class MasterExeCls (models.Model):
    m_exe_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False,
                                              primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    exe_cls = models.CharField(max_length=4, blank=False, null=False)
    exe_cls_nm_1 = models.CharField(max_length=20, blank=False, null=False)
    exe_cls_nm_2 = models.CharField(max_length=20, blank=True, null=True)
    exe_cls_nm_3 = models.CharField(max_length=20, blank=True, null=True)
    exe_cls_nm_4 = models.CharField(max_length=20, blank=True, null=True)
    exe_cls_nm_5 = models.CharField(max_length=20, blank=True, null=True)
    exe_cls_abbr_1 = models.CharField(max_length=8, blank=True, null=True)
    exe_cls_abbr_2 = models.CharField(max_length=8, blank=True, null=True)
    exe_cls_abbr_3 = models.CharField(max_length=8, blank=True, null=True)
    exe_cls_abbr_4 = models.CharField(max_length=8, blank=True, null=True)
    exe_cls_abbr_5 = models.CharField(max_length=8, blank=True, null=True)
    display_order = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    parent_m_exe_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    rem = models.CharField(max_length=2000, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'm_exe_cls'


# 状況コードテーブル　(旧テーブル:状況マスタConditionCode)
class MasterConditionCode(models.Model):
    m_condition_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False,
                                              primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    condition_cd = models.CharField(max_length=4, blank=False, null=False)
    condition_nm_1 = models.CharField(max_length=20, blank=False, null=False)
    condition_nm_2 = models.CharField(max_length=20, blank=True, null=True)
    condition_nm_3 = models.CharField(max_length=20, blank=True, null=True)
    condition_nm_4 = models.CharField(max_length=20, blank=True, null=True)
    condition_nm_5 = models.CharField(max_length=20, blank=True, null=True)
    condition_abbr_1 = models.CharField(max_length=8, blank=True, null=True)
    condition_abbr_2 = models.CharField(max_length=8, blank=True, null=True)
    condition_abbr_3 = models.CharField(max_length=8, blank=True, null=True)
    condition_abbr_4 = models.CharField(max_length=8, blank=True, null=True)
    condition_abbr_5 = models.CharField(max_length=8, blank=True, null=True)
    display_order = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    rem = models.CharField(max_length=2000, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'm_condition_cd'


# 設備台帳基本仕様テーブル(旧テーブル:機器情報EQPT_BASIC_MST)
class FcltyLdgr(models.Model):
    t_fclty_ldgr_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False, primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_location_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    eqpt_id = models.CharField(max_length=20, blank=True, null=True)
    fclty_dstnct_id = models.CharField(max_length=9, blank=False, null=False)
    parent_t_fclty_ldgr_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_fclty_ctg_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_fnc_ctg_1_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_fnc_ctg_2_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_fnc_ctg_3_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_priority_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_proc_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    fclty_status = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True, default=0)
    m_repair_status_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    spare_fclty_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True)
    mntce_methd_cbm = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True, default=0)
    mntce_methd_tbm = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True, default=0)
    mntce_methd_bm = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True, default=0)
    target_qlty = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True, default=0)
    target_environment = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True, default=0)
    fclty_nm = models.CharField(max_length=40, blank=True, null=True)
    loop_no = models.CharField(max_length=20, blank=True, null=True)
    reltd_fclty_no = models.CharField(max_length=20, blank=True, null=True)
    display_specs = models.CharField(max_length=20, blank=True, null=True)
    maker_1_m_cmpny_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    maker_2_m_cmpny_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    model_1 = models.CharField(max_length=30, blank=True, null=True)
    model_2 = models.CharField(max_length=30, blank=True, null=True)
    regulation_cd_1_m_regulation_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    regulation_cd_2_m_regulation_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    regulation_cd_3_m_regulation_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    applied_std_cd_1_m_applied_std_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    applied_std_cd_2_m_applied_std_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    applied_std_cd_3_m_applied_std_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    asset_no = models.CharField(max_length=20, blank=True, null=True)
    oprtn_start_date = models.DateTimeField(blank=True, null=True)
    mfg_no = models.CharField(max_length=20, blank=True, null=True)
    mfg_date = models.DateTimeField(blank=True, null=True)
    instln_place = models.CharField(max_length=30, blank=True, null=True)
    instln_date = models.DateTimeField(blank=True, null=True)
    purch_sub_co_m_cmpny_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    purch_date = models.DateTimeField(blank=True, null=True)
    acqtn_price = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    attch_doc_1 = models.CharField(max_length=100, blank=True, null=True)
    attch_file_1 = models.CharField(max_length=512, blank=True, null=True)
    attch_doc_2 = models.CharField(max_length=100, blank=True, null=True)
    attch_file_2 = models.CharField(max_length=512, blank=True, null=True)
    attch_doc_3 = models.CharField(max_length=100, blank=True, null=True)
    attch_file_3 = models.CharField(max_length=512, blank=True, null=True)
    attch_doc_4 = models.CharField(max_length=100, blank=True, null=True)
    attch_file_4 = models.CharField(max_length=512, blank=True, null=True)
    attch_doc_5 = models.CharField(max_length=100, blank=True, null=True)
    attch_file_5 = models.CharField(max_length=512, blank=True, null=True)
    supplement_data_1 = models.CharField(max_length=100, blank=True, null=True)
    supplement_data_2 = models.CharField(max_length=100, blank=True, null=True)
    fclty_in_chrg_s_user_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    mfg_end_date = models.DateTimeField(blank=True, null=True)
    user_defined_1 = models.CharField(max_length=50, blank=True, null=True)
    user_defined_2 = models.CharField(max_length=50, blank=True, null=True)
    user_defined_3 = models.CharField(max_length=50, blank=True, null=True)
    user_defined_4 = models.CharField(max_length=50, blank=True, null=True)
    user_defined_5 = models.CharField(max_length=50, blank=True, null=True)
    ap_exclusion_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True, default=0)
    u_cost_center = models.CharField(max_length=10, blank=True, null=True)
    u_reg_eqpt_nm = models.CharField(max_length=30, blank=True, null=True)
    u_reg_area = models.CharField(max_length=20, blank=True, null=True)
    u_e_importance = models.CharField(max_length=30, blank=True, null=True)
    latest_rev_chg_reason = models.CharField(max_length=2000, blank=True, null=True)
    latest_rev = models.DecimalField(max_digits=10, decimal_places=0, default=1, blank=False, null=False)
    latest_rev_m_chg_reason_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)
    eqpt_id_mgt_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True, default=0)
    thumbnail_image_doc_1 = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_image_file_1 = models.CharField(max_length=512, blank=True, null=True)
    thumbnail_image_doc_2 = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_image_file_2 = models.CharField(max_length=512, blank=True, null=True)
    thumbnail_image_doc_3 = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_image_file_3 = models.CharField(max_length=512, blank=True, null=True)
    thumbnail_image_doc_4 = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_image_file_4 = models.CharField(max_length=512, blank=True, null=True)
    thumbnail_image_doc_5 = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_image_file_5 = models.CharField(max_length=512, blank=True, null=True)
    thumbnail_image_doc_6 = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_image_file_6 = models.CharField(max_length=512, blank=True, null=True)
    thumbnail_image_doc_7 = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_image_file_7 = models.CharField(max_length=512, blank=True, null=True)
    thumbnail_image_doc_8 = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_image_file_8 = models.CharField(max_length=512, blank=True, null=True)
    thumbnail_image_doc_9 = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_image_file_9 = models.CharField(max_length=512, blank=True, null=True)
    thumbnail_image_doc_10 = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_image_file_10 = models.CharField(max_length=512, blank=True, null=True)
    u_regulation_cd_4 = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    u_regulation_cd_5 = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_fclty_ldgr'


# 原因コードテーブル(旧テーブル:原因コードマスタCAUSE_CD)
class MasterCauseCode(models.Model):
    m_cause_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False, primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    cause_cd = models.CharField(max_length=4, blank=False, null=False)
    cause_nm_1 = models.CharField(max_length=20, blank=False, null=False)
    cause_nm_2 = models.CharField(max_length=20, blank=True, null=True)
    cause_nm_3 = models.CharField(max_length=20, blank=True, null=True)
    cause_nm_4 = models.CharField(max_length=20, blank=True, null=True)
    cause_nm_5 = models.CharField(max_length=20, blank=True, null=True)
    cause_abbr_1 = models.CharField(max_length=8, blank=True, null=True)
    cause_abbr_2 = models.CharField(max_length=8, blank=True, null=True)
    cause_abbr_3 = models.CharField(max_length=8, blank=True, null=True)
    cause_abbr_4 = models.CharField(max_length=8, blank=True, null=True)
    cause_abbr_5 = models.CharField(max_length=8, blank=True, null=True)
    display_order = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    rem = models.CharField(max_length=2000, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'm_cause_cd'


# 結果コードテーブル(旧テーブル:結果コードマスタResultCode)
class MasterResultCode(models.Model):
    m_result_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False, primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    result_cd = models.CharField(max_length=4, blank=False, null=False)
    result_nm_1 = models.CharField(max_length=20, blank=False, null=False)
    result_nm_2 = models.CharField(max_length=20, blank=True, null=True)
    result_nm_3 = models.CharField(max_length=20, blank=True, null=True)
    result_nm_4 = models.CharField(max_length=20, blank=True, null=True)
    result_nm_5 = models.CharField(max_length=20, blank=True, null=True)
    result_abbr_1 = models.CharField(max_length=8, blank=True, null=True)
    result_abbr_2 = models.CharField(max_length=8, blank=True, null=True)
    result_abbr_3 = models.CharField(max_length=8, blank=True, null=True)
    result_abbr_4 = models.CharField(max_length=8, blank=True, null=True)
    result_abbr_5 = models.CharField(max_length=8, blank=True, null=True)
    display_order = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    rem = models.CharField(max_length=2000, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'm_result_cd'


# 現象コードテーブル(旧テーブル:症状コードマスタPHENOMENON_CD)
class MasterPhenomenonCode(models.Model):
    m_phenomenon_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False,
                                               primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    phenomenon_cd = models.CharField(max_length=4, blank=False, null=False)
    phenomenon_nm_1 = models.CharField(max_length=20, blank=False, null=False)
    phenomenon_nm_2 = models.CharField(max_length=20, blank=True, null=True)
    phenomenon_nm_3 = models.CharField(max_length=20, blank=True, null=True)
    phenomenon_nm_4 = models.CharField(max_length=20, blank=True, null=True)
    phenomenon_nm_5 = models.CharField(max_length=20, blank=True, null=True)
    phenomenon_abbr_1 = models.CharField(max_length=8, blank=True, null=True)
    phenomenon_abbr_2 = models.CharField(max_length=8, blank=True, null=True)
    phenomenon_abbr_3 = models.CharField(max_length=8, blank=True, null=True)
    phenomenon_abbr_4 = models.CharField(max_length=8, blank=True, null=True)
    phenomenon_abbr_5 = models.CharField(max_length=8, blank=True, null=True)
    display_order = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    rem = models.CharField(max_length=2000, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'm_phenomenon_cd'


# 保全履歴テーブル(旧テーブル:機器履歴情報MNTCE_LDGR)
class MntceLdgr(models.Model):
    t_mntce_ldgr_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False, primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_location_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    eqpt_id = models.CharField(max_length=20, blank=True, null=True)
    hist_no = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
    t_fclty_ldgr_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    fclty_nm = models.CharField(max_length=40, blank=True, null=True)
    t_mntce_plan_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_fnc_ctg_1_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    fnc_ctg_1_cd = models.CharField(max_length=10, blank=True, null=True)
    fnc_ctg_1_nm_1 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_1_nm_2 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_1_nm_3 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_1_nm_4 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_1_nm_5 = models.CharField(max_length=40, blank=True, null=True)
    m_fnc_ctg_2_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    fnc_ctg_2_cd = models.CharField(max_length=10, blank=True, null=True)
    fnc_ctg_2_nm_1 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_2_nm_2 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_2_nm_3 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_2_nm_4 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_2_nm_5 = models.CharField(max_length=40, blank=True, null=True)
    m_fnc_ctg_3_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    fnc_ctg_3_cd = models.CharField(max_length=10, blank=True, null=True)
    fnc_ctg_3_nm_1 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_3_nm_2 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_3_nm_3 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_3_nm_4 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_3_nm_5 = models.CharField(max_length=40, blank=True, null=True)
    m_proc_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    proc_cd = models.CharField(max_length=10, blank=True, null=True)
    proc_nm_1 = models.CharField(max_length=40, blank=True, null=True)
    proc_nm_2 = models.CharField(max_length=40, blank=True, null=True)
    proc_nm_3 = models.CharField(max_length=40, blank=True, null=True)
    proc_nm_4 = models.CharField(max_length=40, blank=True, null=True)
    proc_nm_5 = models.CharField(max_length=40, blank=True, null=True)
    asset_no = models.CharField(max_length=20, blank=True, null=True)
    mfg_no = models.CharField(max_length=20, blank=True, null=True)
    loop_no = models.CharField(max_length=20, blank=True, null=True)
    reltd_fclty_no = models.CharField(max_length=20, blank=True, null=True)
    t_mntce_mgt_no_hist_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_exe_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    t_mntce_cycle_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    cycle_std_date = models.DateTimeField(blank=False, null=False)
    mntce_nm = models.CharField(max_length=100, blank=True, null=True)
    start_date = models.DateTimeField(blank=False, null=False)
    compltn_date = models.DateTimeField(blank=False, null=False)
    wk_ord_in_chrg_s_user_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    t_repair_item_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    rem = models.CharField(max_length=2000, blank=True, null=True)
    attch_doc_1 = models.CharField(max_length=100, blank=True, null=True)
    attch_file_1 = models.CharField(max_length=512, blank=True, null=True)
    attch_doc_2 = models.CharField(max_length=100, blank=True, null=True)
    attch_file_2 = models.CharField(max_length=512, blank=True, null=True)
    attch_doc_3 = models.CharField(max_length=100, blank=True, null=True)
    attch_file_3 = models.CharField(max_length=512, blank=True, null=True)
    shelved = models.DecimalField(max_digits=1, decimal_places=0, default=0)
    note = models.CharField(max_length=2000, blank=True, null=True)
    nxt_mntce_rem = models.CharField(max_length=2000, blank=True, null=True)
    m_condition_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    condition_m_position_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_phenomenon_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    phenomenon_m_position_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_cause_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    cause_m_position_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_treatment_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    treatment_m_position_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_result_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    occur_dt = models.DateTimeField(blank=False, null=False)
    oprtn_time = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    down_time = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    repair_time = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    mh_in_house = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    mh_sub_con = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    labor_cst = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    matl_cst = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    user_defined_1 = models.CharField(max_length=50, blank=True, null=True)
    user_defined_2 = models.CharField(max_length=50, blank=True, null=True)
    user_defined_3 = models.CharField(max_length=50, blank=True, null=True)
    user_defined_4 = models.CharField(max_length=50, blank=True, null=True)
    user_defined_5 = models.CharField(max_length=50, blank=True, null=True)
    created_compltn = models.DecimalField(max_digits=1, decimal_places=0, default=0)
    order_cls_nm_1 = models.CharField(max_length=1000, blank=True, null=True)
    order_cls_nm_2 = models.CharField(max_length=1000, blank=True, null=True)
    order_cls_nm_3 = models.CharField(max_length=1000, blank=True, null=True)
    test_contents = models.CharField(max_length=1000, blank=True, null=True)
    attch_doc_4 = models.CharField(max_length=100, blank=True, null=True)
    attch_file_4 = models.CharField(max_length=512, blank=True, null=True)
    attch_doc_5 = models.CharField(max_length=100, blank=True, null=True)
    attch_file_5 = models.CharField(max_length=512, blank=True, null=True)
    priority = models.CharField(max_length=4, blank=True, null=True)
    m_progress_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    cycle_std_date_calendar = models.DateTimeField(blank=False, null=False)
    cycle_std_date_plan = models.DateTimeField(blank=False, null=False)
    start_sched_date_plan = models.DateTimeField(blank=False, null=False)
    end_sched_date_plan = models.DateTimeField(blank=False, null=False)
    oprtn_time_plan = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    down_time_plan = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    repair_time_plan = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    mh_plan = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    mh_sub_con_plan = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    labor_cst_calendar = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    labor_cst_plan = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    matl_cst_calendar = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    matl_cst_plan = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    latest_rev_chg_reason = models.CharField(max_length=2000, blank=True, null=True)
    latest_rev = models.DecimalField(max_digits=10, decimal_places=0, blank=False, null=False, default=0)
    latest_rev_m_chg_reason_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    u_mntce_code = models.CharField(max_length=10, blank=True, null=True)
    u_reg_code = models.CharField(max_length=10, blank=True, null=True)
    u_caus_opt = models.CharField(max_length=200, blank=True, null=True)
    u_caus_mnt = models.CharField(max_length=200, blank=True, null=True)
    u_ctms_opt = models.CharField(max_length=200, blank=True, null=True)
    u_ctms_mnt = models.CharField(max_length=200, blank=True, null=True)
    u_phenom = models.CharField(max_length=200, blank=True, null=True)
    u_admission_decision = models.CharField(max_length=10, blank=True, null=True)
    u_construction_num = models.CharField(max_length=10, blank=True, null=True)
    u_registrant = models.CharField(max_length=30, blank=True, null=True)
    u_nxt_mntce_rem_opt = models.CharField(max_length=200, blank=True, null=True)
    u_nxt_mntce_rem_mnt = models.CharField(max_length=200, blank=True, null=True)
    u_notes_opt = models.CharField(max_length=200, blank=True, null=True)
    u_notes_mnt = models.CharField(max_length=200, blank=True, null=True)
    u_work_code = models.CharField(max_length=10, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)
    m_priority_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    fclty_priority_nm_1 = models.CharField(max_length=20, blank=True, null=True)
    fclty_priority_nm_2 = models.CharField(max_length=20, blank=True, null=True)
    fclty_priority_nm_3 = models.CharField(max_length=20, blank=True, null=True)
    fclty_priority_nm_4 = models.CharField(max_length=20, blank=True, null=True)
    fclty_priority_nm_5 = models.CharField(max_length=20, blank=True, null=True)
    mgt_cls = models.CharField(max_length=1, blank=True, null=True)
    mgt_cls_nm_1 = models.CharField(max_length=10, blank=True, null=True)
    mgt_cls_nm_2 = models.CharField(max_length=10, blank=True, null=True)
    mgt_cls_nm_3 = models.CharField(max_length=10, blank=True, null=True)
    mgt_cls_nm_4 = models.CharField(max_length=10, blank=True, null=True)
    mgt_cls_nm_5 = models.CharField(max_length=10, blank=True, null=True)
    location_cd = models.CharField(max_length=50, blank=True, null=True)
    location_nm_1 = models.CharField(max_length=1000, blank=True, null=True)
    location_nm_2 = models.CharField(max_length=1000, blank=True, null=True)
    location_nm_3 = models.CharField(max_length=1000, blank=True, null=True)
    location_nm_4 = models.CharField(max_length=1000, blank=True, null=True)
    location_nm_5 = models.CharField(max_length=1000, blank=True, null=True)
    fclty_dstnct_id = models.CharField(max_length=9, blank=True, null=True)
    m_fclty_ctg_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    fclty_ctg_id = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    fclty_ctg_nm_1 = models.CharField(max_length=40, blank=True, null=True)
    fclty_ctg_nm_2 = models.CharField(max_length=40, blank=True, null=True)
    fclty_ctg_nm_3 = models.CharField(max_length=40, blank=True, null=True)
    fclty_ctg_nm_4 = models.CharField(max_length=40, blank=True, null=True)
    fclty_ctg_nm_5 = models.CharField(max_length=40, blank=True, null=True)
    u_mainte_person1 = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    u_mainte_person2 = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    u_priority = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_mntce_ldgr'


# 機能分類テーブル(旧テーブル:機器ファミリマスタEQPT_FMLY_MST、PLANTIAの機器型マスタEQPT_CATEGORYが統合)
class MasterFncCtg(models.Model):
    m_fnc_ctg_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False, primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    fnc_ctg_cd = models.CharField(max_length=10, blank=False, null=False)  # EQPT_FMLY＋EQPT_TP
    fnc_ctg_nm_1 = models.CharField(max_length=40, blank=False, null=False)
    fnc_ctg_nm_2 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_nm_3 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_nm_4 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_nm_5 = models.CharField(max_length=40, blank=True, null=True)
    fnc_ctg_abbr_1 = models.CharField(max_length=8, blank=True, null=True)
    fnc_ctg_abbr_2 = models.CharField(max_length=8, blank=True, null=True)
    fnc_ctg_abbr_3 = models.CharField(max_length=8, blank=True, null=True)
    fnc_ctg_abbr_4 = models.CharField(max_length=8, blank=True, null=True)
    fnc_ctg_abbr_5 = models.CharField(max_length=8, blank=True, null=True)
    parent_m_fnc_ctg_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    dtl_specs_created_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True)
    display_order = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'm_fnc_ctg'


# 部位コードテーブル
class MasterPositionCode(models.Model):
    m_position_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False,
                                              primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    position_cd = models.CharField(max_length=10, blank=False, null=False)
    top_cls = models.CharField(max_length=20, blank=True, null=True)
    least_cls = models.CharField(max_length=20, blank=True, null=True)
    position_nm_1 = models.CharField(max_length=20, blank=False, null=False)
    position_nm_2 = models.CharField(max_length=20, blank=True, null=True)
    position_nm_3 = models.CharField(max_length=20, blank=True, null=True)
    position_nm_4 = models.CharField(max_length=20, blank=True, null=True)
    position_nm_5 = models.CharField(max_length=20, blank=True, null=True)
    position_abbr_1 = models.CharField(max_length=8, blank=True, null=True)
    position_abbr_2 = models.CharField(max_length=8, blank=True, null=True)
    position_abbr_3 = models.CharField(max_length=8, blank=True, null=True)
    position_abbr_4 = models.CharField(max_length=8, blank=True, null=True)
    position_abbr_5 = models.CharField(max_length=8, blank=True, null=True)
    display_order = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    rem = models.CharField(max_length=2000, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'm_position_cd'


# 処置コードテーブル
class MasterTreatmentCode(models.Model):
    m_treatment_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False,
                                              primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False)
    m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    treatment_cd = models.CharField(max_length=4, blank=False, null=False)
    treatment_nm_1 = models.CharField(max_length=20, blank=False, null=False)
    treatment_nm_2 = models.CharField(max_length=20, blank=True, null=True)
    treatment_nm_3 = models.CharField(max_length=20, blank=True, null=True)
    treatment_nm_4 = models.CharField(max_length=20, blank=True, null=True)
    treatment_nm_5 = models.CharField(max_length=20, blank=True, null=True)
    treatment_abbr_1 = models.CharField(max_length=8, blank=True, null=True)
    treatment_abbr_2 = models.CharField(max_length=8, blank=True, null=True)
    treatment_abbr_3 = models.CharField(max_length=8, blank=True, null=True)
    treatment_abbr_4 = models.CharField(max_length=8, blank=True, null=True)
    treatment_abbr_5 = models.CharField(max_length=8, blank=True, null=True)
    display_order = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    rem = models.CharField(max_length=2000, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'm_treatment_cd'


# ユーザー作成リスト
class ServiceSpecmanList(models.Model):
    s_specman_list_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False,
                                              primary_key=True)
    list_nm = models.CharField(max_length=30, blank=True, null=True)
    allow_edit = models.CharField(max_length=1, blank=True, null=True)
    cmnt = models.CharField(max_length=100, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 's_specman_list'


# ユーザー作成リスト
class ServiceSpecmanListValue(models.Model):
    s_specman_list_value_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False,
                                              primary_key=True)
    s_specman_list_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    seq = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
    display_value_1 = models.CharField(max_length=30, blank=True, null=True)
    display_value_2 = models.CharField(max_length=30, blank=True, null=True)
    display_value_3 = models.CharField(max_length=30, blank=True, null=True)
    display_value_4 = models.CharField(max_length=30, blank=True, null=True)
    display_value_5 = models.CharField(max_length=30, blank=True, null=True)
    internal_value = models.CharField(max_length=30, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 's_specman_list_value'


# ユーザーマスタ
class ServiceUser(models.Model):
    s_user_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=False, null=False, primary_key=True)
    m_site_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    user_id = models.CharField(max_length=10, blank=True, null=True)
    m_post_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    s_system_role_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    m_organization_cd_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    s_approval_lmt_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    s_attch_file_root_acs_role_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    s_fclty_acs_permission_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    s_lmt_subsystem_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    s_site_acs_permission_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    s_widget_acs_permission_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    s_report_lmt_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    passwd_chg = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True)
    other_mgt_cls = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True)
    registration_cls = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True)
    quick_sort_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=True, null=True)
    mgt_cls_in_charge = models.CharField(max_length=200, blank=True, null=True)
    ini_m_mgt_cls_skey = models.DecimalField(max_digits=38, decimal_places=0, blank=True, null=True)
    user_nm = models.CharField(max_length=20, blank=True, null=True)
    passwd = models.CharField(max_length=64, blank=True, null=True)
    passwd_salt = models.CharField(max_length=32, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    passwd_update_dt = models.DateTimeField(blank=False, null=False)
    passwd_input_err_freq = models.DecimalField(max_digits=2, decimal_places=0, blank=True, null=True)
    rem = models.CharField(max_length=2000, blank=True, null=True)
    deleted_flg = models.DecimalField(max_digits=1, decimal_places=0, blank=False, null=False, default=0)
    created_dt = models.DateTimeField(blank=False, null=False)
    created_id = models.CharField(max_length=50, blank=False, null=False)
    created_app = models.CharField(max_length=50, blank=False, null=False)
    update_dt = models.DateTimeField(blank=False, null=False)
    update_id = models.CharField(max_length=50, blank=False, null=False)
    update_app = models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        managed = False
        db_table = 's_user'
