# Generated by Django 2.1.12 on 2021-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecuteLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.IntegerField(blank=True, null=True, verbose_name='プログラムid')),
                ('operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='実行者')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.IntegerField(blank=True, null=True, verbose_name='プログラムid')),
                ('source_file_path', models.CharField(blank=True, max_length=50, null=True, verbose_name='ソースファイル保存パス')),
                ('source_file_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='ソースファイル名')),
                ('post_to_file_path', models.CharField(blank=True, max_length=50, null=True, verbose_name='転記先ファイル保存パス')),
                ('post_to_file_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='転記先ファイル名')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramEntryLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.IntegerField(blank=True, null=True, verbose_name='プログラムid')),
                ('program_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='プログラム名')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='説明')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('source_file_path', models.CharField(blank=True, max_length=50, null=True, verbose_name='ソースファイル保存パス')),
                ('source_file_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='ソースファイル名')),
                ('post_to_file_path', models.CharField(blank=True, max_length=50, null=True, verbose_name='転記先ファイル保存パス')),
                ('post_to_file_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='転記先ファイル名')),
                ('entry_date', models.DateTimeField(blank=True, null=True, verbose_name='登録日時')),
                ('entry_operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='登録者')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='プログラム名')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='説明')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('entry_date', models.DateTimeField(blank=True, null=True, verbose_name='登録日時')),
                ('entry_operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='登録者')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEntryLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(blank=True, null=True, verbose_name='タスクid')),
                ('source_sheet_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='ソースシート名')),
                ('source_cell_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='ソースセル名')),
                ('post_to_sheet_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='転記先シート名')),
                ('post_to_cell_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='転記先セル名')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('entry_date', models.DateTimeField(blank=True, null=True, verbose_name='登録日時')),
                ('entry_operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='登録者')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.IntegerField(blank=True, null=True, verbose_name='プログラムid')),
                ('source_sheet_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='ソースシート名')),
                ('source_cell_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='ソースセル名')),
                ('post_to_sheet_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='転記先シート名')),
                ('post_to_cell_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='転記先セル名')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('entry_date', models.DateTimeField(blank=True, null=True, verbose_name='登録日時')),
                ('entry_operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='登録者')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('update_operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='更新者')),
                ('test_flag', models.IntegerField(blank=True, null=True, verbose_name='テストFL')),
            ],
        ),
    ]
