# Generated by Django 2.1.12 on 2022-03-04 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMaster',
            fields=[
                ('action', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='作業CD')),
                ('action_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='作業名')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'actionmaster',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_table_id', models.IntegerField(blank=True, null=True, verbose_name='対象ID')),
                ('operation_datetime', models.DateTimeField(blank=True, null=True, verbose_name='作業日時')),
                ('operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='作業者')),
                ('operator_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='作業者部署')),
                ('comment', models.CharField(blank=True, max_length=800, null=True, verbose_name='コメント')),
                ('action', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.ActionMaster', verbose_name='作業CD')),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='PageMaster',
            fields=[
                ('page', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ページID')),
                ('page_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='ページ名')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'pagemaster',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='現作業部署')),
                ('present_operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='現作業者')),
            ],
            options={
                'db_table': 'progress',
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='タイトル')),
            ],
            options={
                'db_table': 'quality',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='変更管理名称')),
                ('division', models.CharField(blank=True, max_length=40, null=True, verbose_name='部門名')),
                ('department', models.CharField(blank=True, max_length=40, null=True, verbose_name='部署名')),
                ('user', models.CharField(blank=True, max_length=40, null=True, verbose_name='申請者')),
                ('method', models.CharField(blank=True, max_length=40, null=True, verbose_name='変更対象_方法')),
                ('facility', models.CharField(blank=True, max_length=40, null=True, verbose_name='変更対象_設備')),
                ('material', models.CharField(blank=True, max_length=40, null=True, verbose_name='変更対象_原料/副原料')),
                ('man', models.CharField(blank=True, max_length=40, null=True, verbose_name='変更対象_人')),
                ('others', models.CharField(blank=True, max_length=40, null=True, verbose_name='その他')),
                ('level', models.CharField(blank=True, max_length=40, null=True, verbose_name='継続/一過性')),
                ('treatment', models.CharField(blank=True, max_length=40, null=True, verbose_name='リスク低減処置')),
                ('safety_aspect', models.CharField(blank=True, max_length=40, null=True, verbose_name='評価レベル_安全面')),
                ('quality_aspect', models.CharField(blank=True, max_length=40, null=True, verbose_name='評価レベル_品質面')),
                ('delivery_date', models.DateField(blank=True, max_length=40, null=True, verbose_name='変更希望日')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='タイトル')),
                ('request', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.Request', verbose_name='依頼ID')),
            ],
            options={
                'db_table': 'safety',
            },
        ),
        migrations.CreateModel(
            name='StepAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('action', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.ActionMaster', verbose_name='作業CD')),
            ],
            options={
                'db_table': 'stepaction',
            },
        ),
        migrations.CreateModel(
            name='StepChargeDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='担当部署')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'stepchargedepartment',
            },
        ),
        migrations.CreateModel(
            name='StepDisplayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.IntegerField(blank=True, null=True, verbose_name='ページNO')),
                ('default_page', models.IntegerField(blank=True, null=True, verbose_name='初期ページ')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.PageMaster', verbose_name='ページID')),
            ],
            options={
                'db_table': 'stepdisplayitem',
            },
        ),
        migrations.CreateModel(
            name='StepMaster',
            fields=[
                ('step', models.IntegerField(primary_key=True, serialize=False, verbose_name='工程ID')),
                ('step_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='工程名')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'm_step',
            },
        ),
        migrations.CreateModel(
            name='StepRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='進行方向')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('next_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steprelation_next_step', to='quality_change_management.StepMaster', verbose_name='次工程ID')),
                ('present_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steprelation_present_step', to='quality_change_management.StepMaster', verbose_name='工程ID')),
            ],
            options={
                'db_table': 'steprelation',
            },
        ),
        migrations.CreateModel(
            name='TargetMaster',
            fields=[
                ('target', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='対象')),
                ('target_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='対象名')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
            ],
            options={
                'db_table': 'targetmaster',
            },
        ),
        migrations.AddField(
            model_name='stepmaster',
            name='target',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.TargetMaster', verbose_name='対象'),
        ),
        migrations.AddField(
            model_name='stepdisplayitem',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.StepMaster', verbose_name='工程ID'),
        ),
        migrations.AddField(
            model_name='stepchargedepartment',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.StepMaster', verbose_name='工程ID'),
        ),
        migrations.AddField(
            model_name='stepchargedepartment',
            name='target',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.TargetMaster', verbose_name='対象'),
        ),
        migrations.AddField(
            model_name='stepaction',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.StepMaster', verbose_name='工程ID'),
        ),
        migrations.AddField(
            model_name='stepaction',
            name='target',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.TargetMaster', verbose_name='対象'),
        ),
        migrations.AddField(
            model_name='quality',
            name='request',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.Request', verbose_name='依頼ID'),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress_last_step', to='quality_change_management.StepMaster', verbose_name='前工程ID'),
        ),
        migrations.AddField(
            model_name='progress',
            name='present_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress_present_step', to='quality_change_management.StepMaster', verbose_name='現工程ID'),
        ),
        migrations.AddField(
            model_name='progress',
            name='request',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.Request', verbose_name='依頼ID'),
        ),
        migrations.AddField(
            model_name='log',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.StepMaster', verbose_name='工程ID'),
        ),
        migrations.AddField(
            model_name='log',
            name='target',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.TargetMaster', verbose_name='対象'),
        ),
    ]
