# Generated by Django 2.1.12 on 2022-03-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepchargedepartment',
            name='display_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='steprelation',
            name='display_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='表示順'),
        ),
    ]
