# Generated by Django 2.1.12 on 2022-03-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0002_auto_20220310_1238'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='targetmaster',
            table='m_target',
        ),
    ]
