# Generated by Django 2.1.12 on 2022-03-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0003_auto_20220310_1312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actionmaster',
            table='m_action',
        ),
        migrations.AlterModelTable(
            name='pagemaster',
            table='m_page',
        ),
    ]
