# Generated by Django 2.1.12 on 2022-03-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0004_auto_20220310_1313'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='t_log',
        ),
        migrations.AlterModelTable(
            name='progress',
            table='t_progress',
        ),
        migrations.AlterModelTable(
            name='quality',
            table='t_quality',
        ),
        migrations.AlterModelTable(
            name='request',
            table='t_request',
        ),
        migrations.AlterModelTable(
            name='safety',
            table='t_safety',
        ),
        migrations.AlterModelTable(
            name='stepaction',
            table='m_step_action',
        ),
        migrations.AlterModelTable(
            name='stepchargedepartment',
            table='m_step_charge_department',
        ),
        migrations.AlterModelTable(
            name='stepdisplayitem',
            table='m_step_display_item',
        ),
        migrations.AlterModelTable(
            name='steprelation',
            table='m_step_relation',
        ),
    ]
