# Generated by Django 2.1.12 on 2022-03-31 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0005_auto_20220310_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepPageEntryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_flag', models.IntegerField(blank=True, null=True, verbose_name='無効FL')),
                ('page', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.PageMaster', verbose_name='ページID')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.StepMaster', verbose_name='工程ID')),
            ],
            options={
                'db_table': 'm_step_page_entry',
            },
        ),
    ]
