# Generated by Django 2.1.12 on 2022-04-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0006_steppageentrymaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepaction',
            name='target',
        ),
        migrations.AddField(
            model_name='actionmaster',
            name='action_authority',
            field=models.IntegerField(blank=True, null=True, verbose_name='作業権限'),
        ),
        migrations.AddField(
            model_name='actionmaster',
            name='action_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='作業属性'),
        ),
    ]
