# Generated by Django 2.1.12 on 2022-04-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0007_auto_20220405_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepaction',
            name='action_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='作業属性'),
        ),
    ]
