# Generated by Django 2.1.12 on 2022-06-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0008_stepaction_action_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepmaster',
            name='target',
        ),
        migrations.AddField(
            model_name='progress',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quality_change_management.TargetMaster', verbose_name='対象'),
        ),
    ]
