# Generated by Django 2.1.12 on 2022-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0009_auto_20220621_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='target',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='対象'),
        ),
    ]
