# Generated by Django 2.1.12 on 2022-06-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0010_auto_20220621_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='request',
        ),
        migrations.RemoveField(
            model_name='safety',
            name='request',
        ),
        migrations.AddField(
            model_name='progress',
            name='present_division',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='現作業部門'),
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
        migrations.DeleteModel(
            name='Safety',
        ),
    ]
