# Generated by Django 2.1.12 on 2022-06-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0011_auto_20220624_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmaster',
            name='hidden_flag',
            field=models.IntegerField(blank=True, null=True, verbose_name='無効FL'),
        ),
    ]
