# Generated by Django 2.1.12 on 2022-07-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0012_stepmaster_hidden_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='outline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='変更内容概略'),
        ),
    ]
