# Generated by Django 2.1.12 on 2022-07-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0013_request_outline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='request',
            name='man',
        ),
        migrations.RemoveField(
            model_name='request',
            name='material',
        ),
        migrations.RemoveField(
            model_name='request',
            name='method',
        ),
        migrations.AddField(
            model_name='request',
            name='change_target',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='変更対象'),
        ),
    ]
