# Generated by Django 2.1.12 on 2022-07-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0014_auto_20220707_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmaster',
            name='progress_transition',
            field=models.IntegerField(blank=True, null=True, verbose_name='進捗遷移'),
        ),
    ]
