# Generated by Django 2.1.12 on 2022-07-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0017_auto_20220719_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppageentrymaster',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='種類'),
        ),
    ]
