# Generated by Django 2.1.12 on 2022-07-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0018_steppageentrymaster_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steppageentrymaster',
            name='type',
        ),
        migrations.AddField(
            model_name='steppageentrymaster',
            name='item_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='項目種類'),
        ),
    ]
