# Generated by Django 2.1.12 on 2022-07-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0020_auto_20220720_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntryMaster',
        ),
        migrations.RemoveField(
            model_name='steppageentrymaster',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='steppageentrymaster',
            name='item',
        ),
    ]
