# Generated by Django 2.1.12 on 2022-07-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0021_auto_20220725_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='完了日'),
        ),
        migrations.AlterField(
            model_name='request',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='変更希望日'),
        ),
        migrations.AlterField(
            model_name='request',
            name='delivery_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='変更日終了'),
        ),
        migrations.AlterField(
            model_name='request',
            name='delivery_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='変更日開始'),
        ),
    ]
