# Generated by Django 2.1.12 on 2022-08-12 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0022_auto_20220729_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 12, 13, 20, 49, 475322), null=True, verbose_name='申請日'),
        ),
    ]
