# Generated by Django 2.1.12 on 2022-09-05 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0024_auto_20220812_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 5, 16, 3, 22, 797630), null=True, verbose_name='申請日'),
        ),
        migrations.AlterField(
            model_name='request',
            name='outline',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='変更内容概略'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='変更管理名称'),
        ),
    ]
