# Generated by Django 2.1.12 on 2022-10-07 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0025_auto_20220905_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 7, 11, 38, 40, 655238), null=True, verbose_name='申請日'),
        ),
    ]
