# Generated by Django 2.1.12 on 2022-10-07 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_change_management', '0026_auto_20221007_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='evaluation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='変更結果評価'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='results',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='対策検討結果'),
        ),
        migrations.AlterField(
            model_name='request',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 7, 11, 39, 28, 485173), null=True, verbose_name='申請日'),
        ),
        migrations.AlterField(
            model_name='safety',
            name='evaluation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='変更結果評価'),
        ),
        migrations.AlterField(
            model_name='safety',
            name='results',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='対策検討結果'),
        ),
    ]
