from django.conf.urls import url
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views
# 20201127y-kawauchi 試し
from .views import training_kawauchi
# from .views import file_loader_views

# parts: html表示URL
# action: ボタンアクションURL

app_name = 'fms'

urlpatterns = [
    # 共通項目：common_views
    path('', views.index, name='fms_top_page'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('level4_step_top/', views.level4_step_top, name='level4_step_top'),
    path('level5_step_top/', views.level5_step_top, name='level5_step_top'),
    path('parts/common/log_list/', views.get_log_lists, name='get_log_lists'),
    path('parts/common/action_button_display/', views.action_button_display, name='action_button_display'),
    path('action/print_csv/', views.print_csv, name='print_csv'),
    path('action/push_task/', views.push_task, name='push_task'),
    # path('parts/select_division/', views.select_division, name='select_division'),
    path('parts/select_department/', views.select_department, name='select_department'),
    path('parts/input_select_division/', views.input_select_division, name='input_select_division'),
    path('parts/input_select_department/', views.input_select_department, name='input_select_department'),
    path('parts/select_work_step/', views.select_work_step, name='select_work_step'),
    path('parts/select_budget_plan/', views.select_budget_plan, name='select_budget_plan'),
    path('action/job_return/', views.job_return, name='job_return'),
    path('action/hold_step/', views.hold_step, name='hold_step'),
    path('action/go_next_step/', views.go_next_step, name='go_next_step'),
    path('parts/common/detail_template/', views.detail_template, name='detail_template'),
    path('action/department_change/', views.change_department, name='department_change'),
    path('action/top_page_detail/', views.top_page_detail, name='top_page_detail'),
    path('parts/input_select_division_without_div_add_name/', views.input_select_division_without_div_add_name, name='input_select_division_without_div_add_name'),
    path('parts/input_select_equipment_list/', views.input_select_equipment_list, name='input_select_equipment_list'),
    path('parts/input_select_condition_list/', views.input_select_condition_list, name='input_select_condition_list'),
    path('parts/select_vendor/', views.select_vendor, name='select_vendor'),
    path('parts/select_discovery_person/', views.select_discovery_person, name='select_discovery_person'),
    path('parts/select_person/', views.select_person, name='select_person'),
    path('parts/select_next_department/', views.select_next_department, name='select_next_department'),
    path('parts/select_next_division/', views.select_next_division, name='select_next_division'),
    path('parts/select_next_step/', views.select_next_step_department, name='select_next_step_department'),
    path('parts/select_next_step_department/', views.next_step_department_select, name='next_step_department_select'),
    path('parts/instruction_no_filter/', views.instruction_no_filter, name='instruction_no_filter'),
    path('parts/cost_center_filter/', views.cost_center_filter, name='instruction_no_filter'),
    path('parts/select_next_division/', views.select_next_division, name='select_next_division'),
    path('parts/select_filter_division/', views.select_filter_division, name='select_filter_division'),
    path('parts/select_filter_department/', views.select_filter_department, name='select_filter_department'),
    # ファイル処理関係
    path('action/file_upload/', views.file_upload, name='file_upload'),
    # path('parts/uploade_file_list/', views.get_upload_file_list, name='get_upload_file_list'),  # 2021/01/01 ueda 追加
    path('action/upload_file_list/', views.file_upload_file_list, name='file_upload_file_list'),
    path('action/file_download/<int:data_id>/', views.file_download, name='file_download'),
    path('action/file_delete/', views.file_delete, name='file_delete'),
    path('action/file_upload_other_type/', views.file_upload_other_type, name='file_upload_other_type'),
    path('parts/common/upload_file_list_other_type/', views.file_upload_file_list_other_type, name='file_upload_file_list_other_type'),
    path('action/attached_file_download/<int:data_id>/<str:file_name>/', views.attached_file_download, name='attached_file_download'),
    path('action/output_file_download/<str:target_folder>/<str:file_name>/', views.output_file_download, name='output_file_download'),
    path('action/input_file_upload/', views.input_file_upload, name='input_file_upload'),
    path('action/server_file_download/', views.server_file_download, name='server_file_download'),
    # メール送信関連
    path('action/mail_send_action/', views.mail_send_action, name='mail_send_action'),

    # イレギュラー処理関係
    path('parts/irregular/irregular_menu/', views.irregular_menu, name='irregular_menu'),
    path('parts/irregular/level5_step_stop/', views.level5_step_stop, name='level5_step_stop'),
    path('parts/irregular/stop_execution_work_lists/', views.get_stop_execution_work_lists, name='get_stop_execution_work_lists'),
    path('parts/irregular/stop_work_filter/', views.stop_work_filter, name='stop_work_filter'),
    path('parts/irregular/stop_work_info/', views.stop_work_info, name='stop_work_info'),
    path('action/stop_work_cause_entry/', views.stop_work_cause_entry, name='stop_work_cause_entry'),
    path('action/cs_forced_termination/', views.cs_forced_termination, name='cs_forced_termination'),
    path('action/stop_budget_progress/', views.stop_budget_progress, name='stop_budget_progress'),
    path('parts/irregular/edit_supplier_master/', views.edit_supplier_master_page, name='edit_supplier_master_page'),
    path('action/edit_supplier_master_entry/', views.edit_supplier_master_entry, name='edit_supplier_master_entry'),

    # 一時的対応関係
    path('parts/temporary_response/temporary_response_menu/', views.temporary_response_menu, name='temporary_response_menu'),
    path('parts/temporary_response/make_ordered_construction_excel/', views.make_ordered_construction_excel_page, name='make_ordered_construction_excel_page'),
    path('action/make_ordered_construction_excel/<str:department>/<str:business_year>/<str:start_date>/<str:end_date>/', views.make_ordered_construction_excel, name='make_ordered_construction_excel'),
    path('parts/temporary_response/make_plantia_import_excel_page/', views.make_plantia_import_excel_page,
         name='make_plantia_import_excel_page'),
    path('parts/temporary_response/end_maintenance_order_filter/', views.end_maintenance_order_filter, name='end_maintenance_order_filter'),
    path('parts/temporary_response/end_maintenance_order_list/', views.end_maintenance_order_list, name='end_maintenance_order_list'),
    path('action/make_plantia_import_excel/', views.make_plantia_import_excel, name='make_plantia_import_excel'),
    path('parts/temporary_response/make_hearing_document_page/', views.make_hearing_document_page,
         name='make_hearing_document_page'),
    path('action/make_hearing_document/', views.make_hearing_document, name='make_hearing_document'),
    path('parts/temporary_response/make_budget_registration_list_page/', views.make_budget_registration_list_page,
         name='make_budget_registration_list_page'),
    path('action/make_budget_registration_list/', views.make_budget_registration_list,
         name='make_budget_registration_list'),
    path('action/import_budget_registration_list/', views.import_budget_registration_list,
         name='import_budget_registration_list'),
    path('parts/temporary_response/make_carry_forward_document_page/', views.make_carry_forward_document_page,
         name='make_carry_forward_document_page'),
    path('action/make_carry_forward_document/', views.make_carry_forward_document, name='make_carry_forward_document'),
    path('parts/temporary_response/go_next_budget_plan_page/', views.go_next_budget_plan_page,
         name='go_next_budget_plan_page'),

    # 進捗工程登録/更新
    path('parts/management/step_edit/', views.step_edit, name='step_edit'),
    path('parts/management/step_list/', views.get_step_list, name='get_step_list'),
    path('parts/management/step_relation_list/', views.get_step_relation_list, name='get_step_relation_list'),
    path('parts/management/step_action_list/', views.get_step_action_list, name='get_step_action_list'),
    path('parts/management/step_display_item_list/', views.get_step_display_item_list, name='get_step_display_item_list'),
    path('parts/management/data_entry_step_list/', views.get_data_entry_step_list, name='get_data_entry_step_list'),
    path('action/step_detail/', views.step_detail, name='step_detail'),
    path('parts/management/action_master_list/', views.get_action_master_list, name='get_action_master_list'),
    path('parts/management/step_management/', views.step_management, name='step_management'),
    path('action/step_display_item_detail/', views.step_display_item_detail, name='step_display_item_detail'),
    path('action/step_action_detail/', views.step_action_detail, name='step_action_detail'),
    path('action/data_entry_step_detail/', views.data_entry_step_detail, name='data_entry_step_detail'),
    path('action/step_data_entry/', views.step_data_entry, name='step_data_entry'),
    path('action/step_data_delete/', views.step_data_delete, name='step_data_delete'),
    path('action/step_display_item_entry/', views.step_display_item_entry, name='step_display_item_entry'),
    path('action/step_display_item_delete/', views.step_display_item_delete, name='step_display_item_delete'),
    path('action/step_action_entry/', views.step_action_entry, name='step_action_entry'),
    path('action/step_action_delete/', views.step_action_delete, name='step_action_delete'),
    path('action/data_entry_step_master_entry/', views.data_entry_step_master_entry, name='data_entry_step_master_entry'),
    path('action/data_entry_step_master_delete/', views.data_entry_step_master_delete, name='data_entry_step_master_delete'),
    path('action/step_relation_entry/', views.step_relation_entry, name='step_relation_entry'),
    path('action/step_relation_delete/', views.step_relation_delete, name='step_relation_delete'),
    # 予算関係：budget_views
    path('parts/budget/budget_detail/', views.budget_detail, name='budget_detail'),
    path('parts/budget/budget_detail/budget_data_info/', views.budget_data_info, name='budget_data_info'),
    path('parts/budget/budget_list/', views.get_budget_lists, name='get_budget_lists'),
    path('parts/budget/budget_filter/', views.budget_filter, name='budget_filter'),
    path('action/budget_entry/', views.budget_entry, name='budget_entry'),
    path('action/budget_mplan_entry/', views.budget_mplan_entry, name='budget_mplan_entry'),
    path('action/budget_copy/', views.budget_copy, name='budget_copy'),
    path('action/copy_budget_material_list_entry/', views.copy_budget_material_list_entry, name='copy_budget_material_list_entry'),
    path('action/copy_budget_law_list_entry/', views.copy_budget_law_list_entry, name='copy_budget_law_list_entry'),
    path('action/copy_budget_equipment_list_entry/', views.copy_budget_equipment_list_entry, name='copy_budget_equipment_list_entry'),
    path('action/copy_required_spec_list_entry/', views.copy_required_spec_list_entry, name='copy_required_spec_list_entry'),
    path('parts/budget/budget_copy_source/', views.budget_copy_source, name='budget_copy_source'),

    path('parts/budget/budget_charge_person_info/', views.budget_charge_person_info, name='budget_charge_person_info'),
    path('action/budget_charge_person_entry/', views.budget_charge_person_entry, name='budget_charge_person_entry'),

    path('action/budget/budget/budget_change_department/', views.budget_change_department, name='budget_change_department'),
    path('action/set_budget_condition/', views.set_budget_condition, name='set_budget_condition'),
    path('action/set_relation_budget_condition/', views.set_relation_budget_condition, name='set_relation_budget_condition'),
    path('action/go_next_budget_plan_list/', views.go_next_budget_plan_list,
         name='go_next_budget_plan_list'),


    # 予算繰越関係：budget_carry_forward_views
    path('action/budget_carry_forward_start/', views.budget_carry_forward_start, name='budget_carry_forward_start'),
    path('parts/budget/budget_carry_forward_list/', views.budget_carry_forward_list, name='budget_carry_forward_list'),
    path('parts/budget/budget_carry_forward_info/', views.budget_carry_forward_info, name='budget_carry_forward_info'),
    path('action/budget_carry_forward_entry/', views.budget_carry_forward_entry, name='budget_carry_forward_entry'),
    path('parts/budget/budget_carry_forward_register/', views.budget_carry_forward_register, name='budget_carry_forward_register'),

    # 予算関係法令/関係機器
    path('parts/budget/budget_law_equipment/', views.budget_law_equipment_data_info, name='budget_law_equipment_data_info'),
    path('parts/law_equipment/budget_law_list/', views.get_budget_law_list, name='get_budget_law_list'),
    path('parts/law_equipment/budget_equipment_list/', views.get_budget_equipment_list, name='get_budget_equipment_list'),
    # path('parts/law_equipment/equipment_master_list/', views.get_equipment_master_list, name='get_equipment_master_list'),
    path('parts/equipment_list/', views.get_equipment_list, name='get_equipment_list'),
    path('parts/reset_equipment_list/', views.reset_equipment_list, name='reset_equipment_list'),
    path('parts/law_equipment/filter_equip_family/', views.filter_equip_family, name='filter_equip_family'),
    path('parts/law_equipment/filter_equip_type/', views.filter_equip_type, name='filter_equip_type'),
    path('parts/law_equipment/filter_facility_code/', views.filter_facility_code, name='filter_facility_code'),
    path('action/select_budget_law/', views.select_budget_law, name='select_budget_law'),
    path('action/select_budget_equipment/', views.select_budget_equipment, name='select_budget_equipment'),
    path('action/budget_law_entry/', views.budget_law_entry, name='budget_law_entry'),
    path('action/work_law_entry/', views.work_law_entry, name='work_law_entry'),
    path('action/budget_equipment_entry/', views.budget_equipment_entry, name='budget_equipment_entry'),
    path('action/work_equipment_entry/', views.work_equipment_entry, name='work_equipment_entry'),
    path('action/budget_law_detail/', views.budget_law_detail, name='budget_law_detail'),
    path('action/budget_equipment_detail/', views.budget_equipment_detail, name='budget_equipment_detail'),
    path('action/budget_law_delete/', views.budget_law_delete, name='budget_law_delete'),
    path('action/budget_equipment_delete/', views.budget_equipment_delete, name='budget_equipment_delete'),
    path('parts/budget/work_equipment/', views.work_equipment_data_info, name='work_equipment_data_info'),
    path('parts/law_equipment/work_equipment_list/', views.get_work_equipment_list, name='get_work_equipment_list'),
    path('action/work_equipment_detail/', views.work_equipment_detail, name='work_equipment_detail'),
    path('action/work_equipment_detail_info/', views.work_equipment_detail_info, name='work_equipment_detail_info'),
    path('action/work_equipment_delete/', views.work_equipment_delete, name='work_equipment_delete'),
    # 取扱物質関係：handling_material_views
    path('parts/budget/handling_material_list/', views.handling_material_list, name='handling_material_list'),
    path('parts/budget/handling_material_my_master_list/', views.handling_material_my_master_list, name='handling_material_my_master_list'),
    path('parts/budget/handling_material_data_info/', views.handling_material_data_info, name='handling_material_data_info'),
    # path('parts/budget/material_master_list/', views.material_master_list, name='material_master_list'),
    path('parts/budget/handling_material_master_list/', views.handling_material_master_list, name='handling_material_master_list'),
    path('action/handling_material_entry/', views.handling_material_entry, name='handling_material_entry'),
    path('action/handling_material_delete/', views.handling_material_delete, name='handling_material_delete'),
    path('action/handling_material_my_master_entry/', views.handling_material_my_master_entry, name='handling_material_my_master_entry'),
    path('action/handling_material_my_master_delete/', views.handling_material_my_master_delete, name='handling_material_my_master_delete'),
    # path('parts/budget/handling_material_detail/', views.handling_material_detail, name='handling_material_detail'),
    # 要求機能関係：required_function_views
    path('parts/budget/required_function_list/', views.required_function_list, name='required_function_list'),
    path('parts/budget/required_function_detail/', views.required_function_data_info, name='required_function_data_info'),
    path('parts/budget/required_function_detail_info/', views.required_function_data_info_2, name='required_function_data_info_2'),
    path('action/required_function_entry/', views.required_function_entry, name='required_function_entry'),
    path('action/required_function_delete/', views.required_function_delete, name='required_function_delete'),
    # 要求仕様関係：required_spec_views
    path('parts/budget/required_spec_info/', views.required_spec_data_info, name='required_spec_data_info'),
    path('action/required_spec_detail/', views.required_spec_detail, name='required_spec_detail'),
    path('action/required_spec_entry/', views.required_spec_entry, name='required_spec_entry'),
    path('action/required_spec_delete/', views.required_spec_delete, name='required_spec_delete'),
    path('parts/budget/required_spec_lists/', views.required_spec_list, name='required_spec_list'),
    # 工事方針概要関係：construction_policy_overview_views
    path('parts/budget/policy_overview_info/', views.policy_overview_data_info, name='policy_overview_data_info'),
    path('action/policy_overview_entry/', views.policy_overview_entry, name='policy_overview_entry'),
    path('action/policy_overview_delete/', views.policy_overview_delete, name='policy_overview_delete'),
    path('action/policy_overview_detail/', views.policy_overview_detail, name='policy_overview_detail'),
    path('parts/budget/policy_overview_lists/', views.policy_overview_list, name='policy_overview_list'),
    # 計画担当者関係:planning_charge_person_views
    path('parts/budget/planning_charge_person_data_info/', views.planning_charge_person_data_info, name='planning_charge_person_data_info'),
    path('action/select_charge_person/', views.select_charge_person, name='select_charge_person'),
    path('action/planning_charge_person_entry/', views.planning_charge_person_entry, name='planning_charge_person_entry'),
    path('action/planning_charge_person_delete/', views.planning_charge_person_delete, name='planning_charge_person_delete'),
    path('parts/budget/budget_planning_charge_person/planning_charge_person_list/', views.get_planning_charge_person_list, name='get_planning_charge_person_list'),
    path('action/planning_charge_person_detail/', views.planning_charge_person_detail, name='planning_charge_person_detail'),

    path('action/planning_charge_person_delete/', views.planning_charge_person_delete,
         name='planning_charge_person_delete'),

    path('action/get_planning_charge_person_user_list/', views.get_planning_charge_person_user_list,
         name='get_planning_charge_person_user_list'),


    # 工事関係
    path('parts/work/work_detail/', views.work_detail, name='work_detail'),
    path('parts/work/work_detail/work_common_data_info/', views.work_common_data_info, name='work_common_data_info'),
    path('action/work_default_entry/', views.work_default_entry, name='work_default_entry'),
    path('action/work_common_entry/', views.work_common_entry, name='work_common_entry'),
    path('parts/work/work_list/', views.get_work_lists, name='get_work_lists'),
    path('parts/work/work_filter/', views.work_filter, name='work_filter'),
    # path('parts/budget/handling_material_data_info/', views.handling_material_data_info, name='handling_material_data_info'), ･･･重複
    # path('parts/work/work_lists_display/', views.work_lists_display, name='work_lists_display'),
    path('action/plan_work_copy/', views.plan_work_copy, name='plan_work_copy'),
    # path('parts/work/execution_work_copy_source/', views.execution_work_copy_source, name='execution_work_copy_source'),
    path('action/copy_free_spec_list_entry/', views.copy_free_spec_list_entry, name='copy_free_spec_list_entry'),
    path('action/copy_equipment_list_entry/', views.copy_equipment_list_entry, name='copy_equipment_list_entry'),
    # 詳細仕様関係
    path('parts/work/template_function/', views.template_function_data_info, name='template_function_data_info'),
    path('parts/work/free_spec_detail/', views.free_function_data_info, name='free_function_data_info'),
    path('action/heat_exchange_spec_entry/', views.heat_exchange_spec_entry, name='heat_exchange_spec_entry'),
    path('action/spec_free_entry/', views.free_function_data_entry, name='free_function_data_entry'),
    path('action/select_free_spec_template/', views.select_free_spec_template, name='select_free_spec_template'),

    # 見積関係
    path('parts/work/estimate/', views.estimate_data_info, name='estimate_data_info'),
    path('parts/estimate/discount_list/', views.discount_list_info, name='discount_list_info'),
    path('action/estimate_entry/', views.estimate_entry, name='estimate_entry'),
    path('parts/work/estimate_work_lists_display/', views.estimate_work_lists_display, name='estimate_work_lists_display'),
    path('action/budget_estimate_entry/', views.budget_estimate_entry, name='budget_estimate_entry'),
    path('action/work_return/', views.work_return, name='work_return'),
    path('action/budget_new_work_entry_complete/', views.budget_new_work_entry_complete, name='budget_new_work_entry_complete'),

    # リスク
    path('parts/work/risks_info/', views.risks_info, name='risks_info'),
    path('action/risks_entry/', views.risks_entry, name='risks_entry'),

    # 提出書類関係
    path('action/select_document/', views.select_document, name='select_document'),
    path('action/document_detail/', views.document_detail, name='document_detail'),
    path('parts/work/document/', views.document_data_info, name='document_data_info'),
    path('parts/document/document_list/', views.get_document_list, name='get_document_list'),
    path('action/document_entry/', views.document_entry, name='document_entry'),
    path('action/document_delete/', views.document_delete, name='document_delete'),

    # 適用法規/支給品類関係
    path('parts/work/work_law_supplies/', views.work_law_supplies_data_info, name='work_law_supplies_data_info'),
    path('parts/law_supplies/work_supplies_list/', views.get_work_supplies_list, name='get_work_supplies_list'),
    path('parts/law_supplies/work_law_list/', views.get_work_law_list, name='get_work_law_list'),
    path('action/select_work_law/', views.select_work_law, name='select_work_law'),
    path('action/select_work_supplies/', views.select_work_supplies, name='select_work_supplies'),
    path('action/work_law_entry/', views.work_law_entry, name='work_law_entry'),
    path('action/work_law_delete/', views.work_law_delete, name='work_law_delete'),
    path('action/work_law_detail/', views.work_law_detail, name='work_law_detail'),
    path('action/work_supplies_entry/', views.work_supplies_entry, name='work_supplies_entry'),
    path('action/work_supplies_delete/', views.work_supplies_delete, name='work_supplies_delete'),
    path('action/work_supplies_detail/', views.work_supplies_detail, name='work_supplies_detail'),

    # 届出cs関係
    path('parts/check_sheet/cs_list/', views.get_cs_lists, name='get_cs_lists'),
    path('parts/check_sheet/cs_filter/', views.cs_filter, name='cs_filter'),
    path('parts/check_sheet/cs_detail/cs_budget_id_filter/', views.cs_budget_id_filter, name='cs_budget_id_filter'),
    path('parts/check_sheet/cs_detail/cs_department_list_filter/', views.cs_department_list_filter, name='cs_department_list_filter'),
    path('parts/check_sheet/cs_detail_template/', views.cs_detail_template, name='cs_detail_template'),
    path('parts/check_sheet/cs_detail/cs_related_laws_list_info/', views.cs_related_laws_list_info, name='cs_related_laws_list_info'),
    path('parts/check_sheet/cs_laws_progress_top_page/', views.cs_laws_progress_top_page, name='cs_laws_progress_top_page'),
    path('parts/check_sheet/cs_laws_progress_filter/', views.cs_laws_progress_filter, name='cs_laws_progress_filter'),
    path('parts/check_sheet/get_cs_laws_progress_list/', views.get_cs_laws_progress_list, name='get_cs_laws_progress_list'),
    path('action/cs_laws_progress_date_entry/', views.cs_laws_progress_date_entry, name='cs_laws_progress_date_entry'),
    path('action/delete_cs_notification_progress/', views.delete_cs_notification_progress, name='delete_cs_notification_progress'),
    path('parts/check_sheet/cs_detail/cs_data_info/', views.cs_data_info, name='cs_data_info'),
    path('action/cs_entry/', views.cs_entry, name='cs_entry'),
    path('action/cs_common_entry/', views.cs_common_entry, name='cs_common_entry'),
    path('parts/check_sheet/cs_detail/cs_safety_health_data_info/', views.cs_safety_health_data_info, name='cs_safety_health_data_info'),
    path('action/cs_safety_health_entry/', views.cs_safety_health_entry, name='cs_safety_health_entry'),
    path('parts/check_sheet/cs_detail/cs_environment_data_info/', views.cs_environment_data_info, name='cs_environment_data_info'),
    path('action/cs_environment_entry/', views.cs_environment_entry, name='cs_environment_entry'),
    path('parts/check_sheet/cs_detail/cs_engineering_data_info/', views.cs_engineering_data_info, name='cs_engineering_data_info'),
    path('action/cs_engineering_entry/', views.cs_engineering_entry, name='cs_engineering_entry'),
    path('parts/check_sheet/cs_detail/cs_log/', views.get_cs_log_lists, name='get_cs_log_lists'),
    path('parts/check_sheet/next_button_display/', views.next_button_display, name='next_button_display'),

    # 工事実行関係
    path('parts/execution/execution_budget_list/', views.get_execution_budget_lists, name='get_execution_budget_lists'),
    path('parts/execution/execution_work_list/', views.get_execution_work_lists, name='get_execution_work_lists'),
    path('parts/execution/execution_budget_filter/', views.execution_budget_filter, name='execution_budget_filter'),
    path('parts/execution/execution_work_filter/', views.execution_work_filter, name='execution_work_filter'),
    path('parts/execution/execution_detail_template/', views.execution_detail_template, name='execution_detail_template'),
    path('parts/execution/probudgetunit_detail_template/', views.probudgetunit_detail_template, name='probudgetunit_detail_template'),
    path('parts/execution/execution_detail/execution_budget_data_info/', views.execution_budget_data_info, name='execution_budget_data_info'),
    path('parts/execution/execution_detail/execution_work_data_info/', views.execution_work_data_info, name='execution_work_data_info'),
    path('action/execution_budget_entry/', views.execution_budget_entry, name='execution_budget_entry'),
    path('action/execution_work_entry/', views.execution_work_entry, name='execution_work_entry'),
    path('parts/execution/execution_provendorevaluation/execution_provendorevaluation_data_info/', views.execution_provendorevaluation_data_info, name='execution_provendorevaluation_data_info'),
    path('parts/execution/execution_proindividualcontractdoc/execution_proindividualcontractdoc_data_info/', views.execution_proindividualcontractdoc_data_info, name='execution_proindividualcontractdoc_data_info'),
    path('action/execution/proindividualcontractdoc/confirmed_vendor_change/', views.confirmed_vendor_change, name='confirmed_vendor_change'),
    path('parts/execution/execution_proinspectionresults/execution_proinspectionresults_data_info/', views.execution_proinspectionresults_data_info, name='execution_proinspectionresults_data_info'),
    path('parts/execution/execution_prodelivery/execution_prodelivery_data_info/', views.execution_prodelivery_data_info, name='execution_prodelivery_data_info'),
    path('parts/execution/execution_proestimates/execution_proestimates_data_info/', views.execution_proestimates_data_info, name='execution_proestimates_data_info'),
    path('parts/execution/execution_proinspection_acceptance/execution_proinspection_acceptance_data_info/', views.execution_proinspection_acceptance_data_info, name='execution_proinspection_acceptance_data_info'),
    path('parts/execution/execution_proconstructionprep/execution_proconstructionprep_data_info/', views.execution_proconstructionprep_data_info, name='execution_proconstructionprep_data_info'),
    path('parts/execution/execution_proconstructionqualityresults/execution_proconstructionqualityresults_data_info/', views.execution_proconstructionqualityresults_data_info, name='execution_proconstructionqualityresults_data_info'),
    path('action/execution_provendorevaluation_entry/', views.execution_provendorevaluation_entry, name='execution_provendorevaluation_entry'),
    path('action/execution_proindividualcontractdoc_entry/', views.execution_proindividualcontractdoc_entry, name='execution_proindividualcontractdoc_entry'),
    path('action/execution_proinspectionresults_entry/', views.execution_proinspectionresults_entry, name='execution_proinspectionresults_entry'),
    path('action/execution_prodelivery_entry/', views.execution_prodelivery_entry, name='execution_prodelivery_entry'),
    path('action/execution_proestimates_entry/', views.execution_proestimates_entry, name='execution_proestimates_entry'),
    path('action/execution_proinspection_acceptance_entry/', views.execution_proinspection_acceptance_entry, name='execution_proinspection_acceptance_entry'),
    path('action/execution_proconstructionprep_entry/', views.execution_proconstructionprep_entry, name='execution_proconstructionprep_entry'),
    path('action/execution_proconstructionqualityresults_entry/', views.execution_proconstructionqualityresults_entry, name='execution_proconstructionqualityresults_entry'),
    path('action/execution_output_application/', views.execution_output_application, name='execution_output_application'),
    path('action/make_complete_report_file/', views.make_complete_report_file, name='make_complete_report_file'),
    path('parts/execution/execution_handling_material_data_info/', views.execution_handling_material_data_info, name='execution_handling_material_data_info'),
    path('parts/execution/execution_handling_material_list/', views.execution_handling_material_list, name='execution_handling_material_list'),
    path('parts/execution/execution_required_function_detail/', views.execution_required_function_data_info, name='execution_required_function_data_info'),
    path('parts/execution/execution_required_function_detail_info/', views.execution_required_function_data_info_2, name='execution_required_function_data_info_2'),
    path('parts/execution/execution_required_function_list/', views.execution_required_function_list, name='execution_required_function_list'),
    path('parts/execution/budget_information/', views.budget_information, name='budget_infomation'),

    # 工事実行コピー
    path('action/execution_work_copy/', views.execution_work_copy, name='execution_work_copy'),
    path('parts/execution/execution_work_copy_source/', views.execution_work_copy_source, name='execution_work_copy_source'),
    path('action/copy_document_list_entry/', views.copy_document_list_entry, name='copy_document_list_entry'),
    path('action/copy_law_supplies_list_entry/', views.copy_law_supplies_list_entry, name='copy_law_supplies_list_entry'),
    path('action/copy_uploadfile_list_entry/', views.copy_uploadfile_list_entry, name='copy_uploadfile_list_entry'),

    # 故障対応
    path('parts/maintenance/phenomenon_data_info/', views.phenomenon_data_info, name='phenomenon_data_info'),
    path('parts/maintenance/measure_data_info/', views.measure_data_info, name='measure_data_info'),
    path('parts/maintenance/notification_check_data_info/', views.notification_check_data_info, name='notification_check_data_info'),
    path('parts/maintenance/inspection_data_info/', views.inspection_data_info, name='inspection_data_info'),
    path('parts/maintenance/maintenance_order_data_info/', views.maintenance_order_data_info, name='maintenance_order_data_info'),
    path('parts/maintenance/maintenance_order_vendor_data_info/', views.maintenance_order_vendor_data_info, name='maintenance_order_vendor_data_info'),
    path('parts/maintenance/maintenance_order_estimates_info/', views.maintenance_order_estimates_data_info, name='maintenance_order_estimates_data_info'),
    path('parts/maintenance/report_maintenance_g_data_info/', views.target_equipment_history_report_data_info, name='target_equipment_history_report_data_info'),
    path('parts/maintenance/report_origin_g_data_info/', views.maintenance_report_origin_g_views.target_equipment_history_report_data_info, name='target_equipment_history_report_data_info'),
    path('parts/maintenance/phenomenon_filter/', views.phenomenon_filter, name='phenomenon_filter'),
    path('parts/maintenance/maintenance_notification_check_filter/', views.notification_check_filter, name='notification_check_filter'),
    path('parts/maintenance/maintenance_list/', views.get_phenomenon_lists, name='get_phenomenon_lists'),
    path('parts/maintenance/notification_check_list/', views.get_notification_check_lists, name='get_notification_check_lists'),
    path('parts/maintenance/phenomenon_copy_source/', views.phenomenon_copy_source, name='phenomenon_copy_source'),
    path('parts/maintenance/maintenance_inspection_acceptance_info/', views.maintenance_inspection_acceptance_info, name='maintenance_inspection_acceptance_info'),
    path('action/phenomenon_entry/', views.phenomenon_entry, name='phenomenon_entry'),
    path('action/measure_entry/', views.measure_entry, name='measure_entry'),

    path('action/maintenance_change_department/', views.maintenance_change_department, name='maintenance_change_department'),

    path('action/measure_change_department/', views.measure_change_department, name='measure_change_department'),
    path('action/notification_check_entry/', views.notification_check_entry, name='notification_check_entry'),
    path('action/inspection_entry/', views.inspection_entry, name='inspection_entry'),
    path('action/action/maintenance_iep_mail_send/', views.maintenance_iep_mail_send, name='maintenance_iep_mail_send'),
    path('action/maintenance_order_entry/', views.maintenance_order_entry, name='maintenance_order_entry'),
    path('action/maintenance_order_estimates_entry/', views.maintenance_order_estimates_entry, name='maintenance_order_estimates_entry'),
    path('action/make_request_estimate_maintenance_order/<int:phenomenon_id>/<int:vendor_no>/', views.make_request_estimate_maintenance_order,
         name='make_request_estimate_maintenance_order'),
    path('action/maintenance_order_vendor_entry/', views.maintenance_order_vendor_entry, name='maintenance_order_vendor_entry'),
    path('action/equipment_history_report_entry/', views.target_equipment_history_report_data_entry, name='target_equipment_history_report_data_entry'),
    path('action/report_origin_g_entry/', views.maintenance_report_origin_g_views.target_equipment_history_report_data_entry, name='target_equipment_history_report_data_entry'),
    path('action/make_request_for_quotation/<int:phenomenon_id>/', views.make_request_for_quotation, name='make_request_for_quotation'),
    path('action/phenomenon_equipment_delete/', views.phenomenon_equipment_delete, name='phenomenon_equipment_delete'),
    path('action/phenomenon_copy/', views.phenomenon_copy, name='phenomenon_copy'),
    path('action/measure_copy/', views.measure_copy, name='measure_copy'),
    path('action/maintenance_inspection_acceptance_entry/', views.maintenance_inspection_acceptance_entry, name='maintenance_inspection_acceptance_entry'),

    # 工事地図表示用
    path('action/construction_data_get/', views.construction_data_get, name='construction_data_get'),
    path('parts/daily_construction/daily_construction_display/', views.daily_construction_display, name='daily_construction_display'),
    path('action/construction_entry_data_get/', views.construction_entry_data_get, name='construction_entry_data_get'),
    path('parts/daily_construction/daily_construction_entry_page/', views.daily_construction_entry_page, name='daily_construction_entry_page'),
    path('action/position_data_entry/', views.position_data_entry, name='position_data_entry'),
    path('action/file_import/', views.file_import, name='file_import'),

    # テスト用
    path('action/add_document_save/', views.additional_document_save, name='additional_document_save'),
    path('action/add_document_read/', views.additional_document_read, name='additional_document_read'),
    # テスト用川内
    path('TEST/<int:id>/<name>/', training_kawauchi.test, name='test'),

]
